// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/poymanov/codemania-task-board/auth/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewJWT creates a new instance of JWT. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewJWT(t interface {
	mock.TestingT
	Cleanup(func())
}) *JWT {
	mock := &JWT{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// JWT is an autogenerated mock type for the JWT type
type JWT struct {
	mock.Mock
}

type JWT_Expecter struct {
	mock *mock.Mock
}

func (_m *JWT) EXPECT() *JWT_Expecter {
	return &JWT_Expecter{mock: &_m.Mock}
}

// GenerateAccessToken provides a mock function for the type JWT
func (_mock *JWT) GenerateAccessToken(user1 user.User) (string, error) {
	ret := _mock.Called(user1)

	if len(ret) == 0 {
		panic("no return value specified for GenerateAccessToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(user.User) (string, error)); ok {
		return returnFunc(user1)
	}
	if returnFunc, ok := ret.Get(0).(func(user.User) string); ok {
		r0 = returnFunc(user1)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(user.User) error); ok {
		r1 = returnFunc(user1)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// JWT_GenerateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateAccessToken'
type JWT_GenerateAccessToken_Call struct {
	*mock.Call
}

// GenerateAccessToken is a helper method to define mock.On call
//   - user1 user.User
func (_e *JWT_Expecter) GenerateAccessToken(user1 interface{}) *JWT_GenerateAccessToken_Call {
	return &JWT_GenerateAccessToken_Call{Call: _e.mock.On("GenerateAccessToken", user1)}
}

func (_c *JWT_GenerateAccessToken_Call) Run(run func(user1 user.User)) *JWT_GenerateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 user.User
		if args[0] != nil {
			arg0 = args[0].(user.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *JWT_GenerateAccessToken_Call) Return(s string, err error) *JWT_GenerateAccessToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *JWT_GenerateAccessToken_Call) RunAndReturn(run func(user1 user.User) (string, error)) *JWT_GenerateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}
