// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/poymanov/codemania-task-board/board/internal/domain/outbox_event"
	mock "github.com/stretchr/testify/mock"
)

// NewOutboxEventRepository creates a new instance of OutboxEventRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOutboxEventRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *OutboxEventRepository {
	mock := &OutboxEventRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// OutboxEventRepository is an autogenerated mock type for the OutboxEventRepository type
type OutboxEventRepository struct {
	mock.Mock
}

type OutboxEventRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *OutboxEventRepository) EXPECT() *OutboxEventRepository_Expecter {
	return &OutboxEventRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type OutboxEventRepository
func (_mock *OutboxEventRepository) Create(ctx context.Context, newEvent outbox_event.NewEvent) error {
	ret := _mock.Called(ctx, newEvent)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, outbox_event.NewEvent) error); ok {
		r0 = returnFunc(ctx, newEvent)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxEventRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type OutboxEventRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newEvent outbox_event.NewEvent
func (_e *OutboxEventRepository_Expecter) Create(ctx interface{}, newEvent interface{}) *OutboxEventRepository_Create_Call {
	return &OutboxEventRepository_Create_Call{Call: _e.mock.On("Create", ctx, newEvent)}
}

func (_c *OutboxEventRepository_Create_Call) Run(run func(ctx context.Context, newEvent outbox_event.NewEvent)) *OutboxEventRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 outbox_event.NewEvent
		if args[1] != nil {
			arg1 = args[1].(outbox_event.NewEvent)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OutboxEventRepository_Create_Call) Return(err error) *OutboxEventRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxEventRepository_Create_Call) RunAndReturn(run func(ctx context.Context, newEvent outbox_event.NewEvent) error) *OutboxEventRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllNotProcessedByType provides a mock function for the type OutboxEventRepository
func (_mock *OutboxEventRepository) GetAllNotProcessedByType(ctx context.Context, entityType string, limit int) ([]outbox_event.OutboxEvent, error) {
	ret := _mock.Called(ctx, entityType, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetAllNotProcessedByType")
	}

	var r0 []outbox_event.OutboxEvent
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) ([]outbox_event.OutboxEvent, error)); ok {
		return returnFunc(ctx, entityType, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int) []outbox_event.OutboxEvent); ok {
		r0 = returnFunc(ctx, entityType, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]outbox_event.OutboxEvent)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int) error); ok {
		r1 = returnFunc(ctx, entityType, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// OutboxEventRepository_GetAllNotProcessedByType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllNotProcessedByType'
type OutboxEventRepository_GetAllNotProcessedByType_Call struct {
	*mock.Call
}

// GetAllNotProcessedByType is a helper method to define mock.On call
//   - ctx context.Context
//   - entityType string
//   - limit int
func (_e *OutboxEventRepository_Expecter) GetAllNotProcessedByType(ctx interface{}, entityType interface{}, limit interface{}) *OutboxEventRepository_GetAllNotProcessedByType_Call {
	return &OutboxEventRepository_GetAllNotProcessedByType_Call{Call: _e.mock.On("GetAllNotProcessedByType", ctx, entityType, limit)}
}

func (_c *OutboxEventRepository_GetAllNotProcessedByType_Call) Run(run func(ctx context.Context, entityType string, limit int)) *OutboxEventRepository_GetAllNotProcessedByType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *OutboxEventRepository_GetAllNotProcessedByType_Call) Return(outboxEvents []outbox_event.OutboxEvent, err error) *OutboxEventRepository_GetAllNotProcessedByType_Call {
	_c.Call.Return(outboxEvents, err)
	return _c
}

func (_c *OutboxEventRepository_GetAllNotProcessedByType_Call) RunAndReturn(run func(ctx context.Context, entityType string, limit int) ([]outbox_event.OutboxEvent, error)) *OutboxEventRepository_GetAllNotProcessedByType_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEventProcessed provides a mock function for the type OutboxEventRepository
func (_mock *OutboxEventRepository) UpdateEventProcessed(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEventProcessed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// OutboxEventRepository_UpdateEventProcessed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEventProcessed'
type OutboxEventRepository_UpdateEventProcessed_Call struct {
	*mock.Call
}

// UpdateEventProcessed is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *OutboxEventRepository_Expecter) UpdateEventProcessed(ctx interface{}, id interface{}) *OutboxEventRepository_UpdateEventProcessed_Call {
	return &OutboxEventRepository_UpdateEventProcessed_Call{Call: _e.mock.On("UpdateEventProcessed", ctx, id)}
}

func (_c *OutboxEventRepository_UpdateEventProcessed_Call) Run(run func(ctx context.Context, id int)) *OutboxEventRepository_UpdateEventProcessed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *OutboxEventRepository_UpdateEventProcessed_Call) Return(err error) *OutboxEventRepository_UpdateEventProcessed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *OutboxEventRepository_UpdateEventProcessed_Call) RunAndReturn(run func(ctx context.Context, id int) error) *OutboxEventRepository_UpdateEventProcessed_Call {
	_c.Call.Return(run)
	return _c
}

// WithTx provides a mock function for the type OutboxEventRepository
func (_mock *OutboxEventRepository) WithTx(tx pgx.Tx) outbox_event.OutboxEventRepository {
	ret := _mock.Called(tx)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 outbox_event.OutboxEventRepository
	if returnFunc, ok := ret.Get(0).(func(pgx.Tx) outbox_event.OutboxEventRepository); ok {
		r0 = returnFunc(tx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(outbox_event.OutboxEventRepository)
		}
	}
	return r0
}

// OutboxEventRepository_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type OutboxEventRepository_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - tx pgx.Tx
func (_e *OutboxEventRepository_Expecter) WithTx(tx interface{}) *OutboxEventRepository_WithTx_Call {
	return &OutboxEventRepository_WithTx_Call{Call: _e.mock.On("WithTx", tx)}
}

func (_c *OutboxEventRepository_WithTx_Call) Run(run func(tx pgx.Tx)) *OutboxEventRepository_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 pgx.Tx
		if args[0] != nil {
			arg0 = args[0].(pgx.Tx)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *OutboxEventRepository_WithTx_Call) Return(outboxEventRepository outbox_event.OutboxEventRepository) *OutboxEventRepository_WithTx_Call {
	_c.Call.Return(outboxEventRepository)
	return _c
}

func (_c *OutboxEventRepository_WithTx_Call) RunAndReturn(run func(tx pgx.Tx) outbox_event.OutboxEventRepository) *OutboxEventRepository_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
