// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	mock "github.com/stretchr/testify/mock"
)

// NewTx creates a new instance of Tx. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTx(t interface {
	mock.TestingT
	Cleanup(func())
}) *Tx {
	mock := &Tx{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Tx is an autogenerated mock type for the Tx type
type Tx struct {
	mock.Mock
}

type Tx_Expecter struct {
	mock *mock.Mock
}

func (_m *Tx) EXPECT() *Tx_Expecter {
	return &Tx_Expecter{mock: &_m.Mock}
}

// WithTx provides a mock function for the type Tx
func (_mock *Tx) WithTx(ctx context.Context, fn func(tx pgx.Tx) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(tx pgx.Tx) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// Tx_WithTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WithTx'
type Tx_WithTx_Call struct {
	*mock.Call
}

// WithTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(tx pgx.Tx) error
func (_e *Tx_Expecter) WithTx(ctx interface{}, fn interface{}) *Tx_WithTx_Call {
	return &Tx_WithTx_Call{Call: _e.mock.On("WithTx", ctx, fn)}
}

func (_c *Tx_WithTx_Call) Run(run func(ctx context.Context, fn func(tx pgx.Tx) error)) *Tx_WithTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(tx pgx.Tx) error
		if args[1] != nil {
			arg1 = args[1].(func(tx pgx.Tx) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *Tx_WithTx_Call) Return(err error) *Tx_WithTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *Tx_WithTx_Call) RunAndReturn(run func(ctx context.Context, fn func(tx pgx.Tx) error) error) *Tx_WithTx_Call {
	_c.Call.Return(run)
	return _c
}
