services:
  board:
    build:
      context: .
      dockerfile: docker/board/Dockerfile
    ports:
      - ${BOARD_GRPC_EXTERNAL_PORT}:${BOARD_GRPC_PORT}
    volumes:
      - '.:/app'
    command: ["go", "run", "board/cmd/main.go"]
    depends_on:
      postgres-board:
        condition: service_healthy
      kafka:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:${LOKI_INTERNAL_PORT}/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                app_name: app_name
                level: level
          - labels:
              app_name:
              level:
  postgres-board:
    image: postgres:17.0-alpine3.20
    volumes:
      - postgres_board_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_POSTGRES_BOARD_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_BOARD_USER}
      POSTGRES_PASSWORD: ${POSTGRES_BOARD_PASSWORD}
      POSTGRES_DB: ${POSTGRES_BOARD_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_BOARD_USER} -d ${POSTGRES_BOARD_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  auth:
    build:
      context: .
      dockerfile: docker/auth/Dockerfile
    ports:
      - ${AUTH_GRPC_EXTERNAL_PORT}:${AUTH_GRPC_PORT}
    volumes:
      - '.:/app'
    command: ["go", "run", "auth/cmd/main.go"]
    depends_on:
      postgres-auth:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:${LOKI_INTERNAL_PORT}/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                app_name: app_name
                level: level
          - labels:
              app_name:
              level:
  postgres-auth:
    image: postgres:17.0-alpine3.20
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    ports:
      - "${EXTERNAL_POSTGRES_AUTH_PORT}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_AUTH_USER}
      POSTGRES_PASSWORD: ${POSTGRES_AUTH_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUTH_DB}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_AUTH_USER} -d ${POSTGRES_AUTH_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
  gateway:
    build:
      context: .
      dockerfile: docker/gateway/Dockerfile
    ports:
      - ${GATEWAY_HTTP_EXTERNAL_PORT}:${GATEWAY_HTTP_PORT}
      - ${GATEWAY_HTTP_METRICS_PORT}:${GATEWAY_HTTP_METRICS_PORT}
    volumes:
      - '.:/app'
    command: ["go", "run", "gateway/cmd/main.go"]
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:${LOKI_INTERNAL_PORT}/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                app_name: app_name
                level: level
          - labels:
              app_name:
              level:
  notification:
    build:
      context: .
      dockerfile: docker/notification/Dockerfile
    volumes:
      - '.:/app'
    command: ["go", "run", "notification/cmd/main.go"]
    depends_on:
      kafka:
        condition: service_healthy
    logging:
      driver: loki
      options:
        loki-url: "http://localhost:${LOKI_INTERNAL_PORT}/loki/api/v1/push"
        loki-pipeline-stages: |
          - json:
              expressions:
                app_name: app_name
                level: level
          - labels:
              app_name:
              level:
  loki:
    image: grafana/loki:3.7
    ports:
      - "${LOKI_EXTERNAL_PORT}:${LOKI_INTERNAL_PORT}"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./docker/common/loki/loki.yaml:/etc/loki/local-config.yaml
  kafka:
    image: confluentinc/cp-kafka:7.9.0
    ports:
      - "${KAFKA_EXTERNAL_PORT}:${KAFKA_EXTERNAL_PORT}"
    environment:
      KAFKA_KRAFT_MODE: "true"
      KAFKA_PROCESS_ROLES: controller,broker
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:${KAFKA_CONTROLLER_PORT}"
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:${KAFKA_INTERNAL_PORT},PLAINTEXT_EXTERNAL://0.0.0.0:${KAFKA_EXTERNAL_PORT},CONTROLLER://kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:${KAFKA_INTERNAL_PORT},PLAINTEXT_EXTERNAL://localhost:${KAFKA_EXTERNAL_PORT},CONTROLLER://kafka:${KAFKA_CONTROLLER_PORT}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      CLUSTER_ID: "Mk3OEYBSD34fcwNTJENDM2Qk"
    volumes:
      - kafka_data:/var/lib/kafka/data
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-c",
          "echo > /dev/tcp/localhost/${KAFKA_INTERNAL_PORT}",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    container_name: kafka-ui
    ports:
      - "${KAFKA_UI_PORT}:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: "local-cluster"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:${KAFKA_INTERNAL_PORT}"
    depends_on:
      kafka:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
  grafana:
    image: grafana/grafana:13.0.0-23649747481
    volumes:
      - ./docker/common/grafana/datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      - ./docker/common/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/default.json
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor traceQLStreaming metricsSummary
    ports:
      - '${GRAFANA_UI_PORT}:3000'
  prometheus:
    image: prom/prometheus:v3
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
      - --enable-feature=exemplar-storage
    volumes:
      - ./docker/common/prometheus/prometheus.yaml:/etc/prometheus.yaml
    ports:
      - '${PROMETHEUS_UI_PORT}:9090'
volumes:
  postgres_board_data:
  postgres_auth_data:
  kafka_data:
networks:
  default:
    name: docker
    external: true