// Code generated by ogen, DO NOT EDIT.

package gateway_v1

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// BoardCreate implements BoardCreate operation.
	//
	// Создание доски.
	//
	// POST /api/v1/boards
	BoardCreate(ctx context.Context, req *CreateBoardRequestBody) (BoardCreateRes, error)
	// BoardGet implements BoardGet operation.
	//
	// Получение доски.
	//
	// GET /api/v1/boards/{id}
	BoardGet(ctx context.Context, params BoardGetParams) (BoardGetRes, error)
	// BoardGetAll implements BoardGetAll operation.
	//
	// Получение досок.
	//
	// GET /api/v1/boards
	BoardGetAll(ctx context.Context) (BoardGetAllRes, error)
	// ColumnCreate implements ColumnCreate operation.
	//
	// Создание колонки.
	//
	// POST /api/v1/boards/{id}/columns
	ColumnCreate(ctx context.Context, req *CreateColumnRequestBody, params ColumnCreateParams) (ColumnCreateRes, error)
	// ColumnDelete implements ColumnDelete operation.
	//
	// Удаление колонки.
	//
	// DELETE /api/v1/boards/{boardId}/columns/{columnId}
	ColumnDelete(ctx context.Context, params ColumnDeleteParams) (ColumnDeleteRes, error)
	// ColumnUpdatePosition implements ColumnUpdatePosition operation.
	//
	// Изменение позиции колонки.
	//
	// PATCH /api/v1/boards/{boardId}/columns/{columnId}/update-position
	ColumnUpdatePosition(ctx context.Context, req *ColumnUpdatePositionRequestBody, params ColumnUpdatePositionParams) (ColumnUpdatePositionRes, error)
	// TaskCreate implements TaskCreate operation.
	//
	// Создание задачи.
	//
	// POST /api/v1/boards/{boardId}/columns/{columnId}/tasks
	TaskCreate(ctx context.Context, req *TaskCreateRequestBody, params TaskCreateParams) (TaskCreateRes, error)
	// TaskDelete implements TaskDelete operation.
	//
	// Удаление задачи.
	//
	// POST /api/v1/boards/{boardId}/columns/{columnId}/tasks/{taskId}
	TaskDelete(ctx context.Context, params TaskDeleteParams) (TaskDeleteRes, error)
	// TaskUpdatePosition implements TaskUpdatePosition operation.
	//
	// Изменение позиции задачи.
	//
	// PATCH /api/v1/boards/{boardId}/columns/{columnId}/tasks/{taskId}/update-position
	TaskUpdatePosition(ctx context.Context, req *TaskUpdatePositionRequestBody, params TaskUpdatePositionParams) (TaskUpdatePositionRes, error)
	// NewError creates *GenericErrorStatusCode from error returned by handler.
	//
	// Used for common default response.
	NewError(ctx context.Context, err error) *GenericErrorStatusCode
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h Handler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		baseServer: s,
	}, nil
}
