// Code generated by ogen, DO NOT EDIT.

package gateway_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	AuthLoginOperation            OperationName = "AuthLogin"
	AuthRegisterOperation         OperationName = "AuthRegister"
	BoardCreateOperation          OperationName = "BoardCreate"
	BoardGetOperation             OperationName = "BoardGet"
	BoardGetAllOperation          OperationName = "BoardGetAll"
	ColumnCreateOperation         OperationName = "ColumnCreate"
	ColumnDeleteOperation         OperationName = "ColumnDelete"
	ColumnUpdatePositionOperation OperationName = "ColumnUpdatePosition"
	TaskCreateOperation           OperationName = "TaskCreate"
	TaskDeleteOperation           OperationName = "TaskDelete"
	TaskUpdatePositionOperation   OperationName = "TaskUpdatePosition"
)
