// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: auth/v1/auth.proto

package auth_v1

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on UserServiceRegisterRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceRegisterRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceRegisterRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceRegisterRequestMultiError, or nil if none found.
func (m *UserServiceRegisterRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceRegisterRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = UserServiceRegisterRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPassword()) < 1 {
		err := UserServiceRegisterRequestValidationError{
			field:  "Password",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetUsername()) < 1 {
		err := UserServiceRegisterRequestValidationError{
			field:  "Username",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserServiceRegisterRequestMultiError(errors)
	}

	return nil
}

func (m *UserServiceRegisterRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *UserServiceRegisterRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// UserServiceRegisterRequestMultiError is an error wrapping multiple
// validation errors returned by UserServiceRegisterRequest.ValidateAll() if
// the designated constraints aren't met.
type UserServiceRegisterRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceRegisterRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceRegisterRequestMultiError) AllErrors() []error { return m }

// UserServiceRegisterRequestValidationError is the validation error returned
// by UserServiceRegisterRequest.Validate if the designated constraints aren't met.
type UserServiceRegisterRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceRegisterRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceRegisterRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceRegisterRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceRegisterRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceRegisterRequestValidationError) ErrorName() string {
	return "UserServiceRegisterRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceRegisterRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceRegisterRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceRegisterRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceRegisterRequestValidationError{}

// Validate checks the field values on UserServiceRegisterResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceRegisterResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceRegisterResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceRegisterResponseMultiError, or nil if none found.
func (m *UserServiceRegisterResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceRegisterResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if len(errors) > 0 {
		return UserServiceRegisterResponseMultiError(errors)
	}

	return nil
}

// UserServiceRegisterResponseMultiError is an error wrapping multiple
// validation errors returned by UserServiceRegisterResponse.ValidateAll() if
// the designated constraints aren't met.
type UserServiceRegisterResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceRegisterResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceRegisterResponseMultiError) AllErrors() []error { return m }

// UserServiceRegisterResponseValidationError is the validation error returned
// by UserServiceRegisterResponse.Validate if the designated constraints
// aren't met.
type UserServiceRegisterResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceRegisterResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceRegisterResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceRegisterResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceRegisterResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceRegisterResponseValidationError) ErrorName() string {
	return "UserServiceRegisterResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceRegisterResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceRegisterResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceRegisterResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceRegisterResponseValidationError{}

// Validate checks the field values on UserServiceLoginRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceLoginRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceLoginRequest with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceLoginRequestMultiError, or nil if none found.
func (m *UserServiceLoginRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceLoginRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if err := m._validateEmail(m.GetEmail()); err != nil {
		err = UserServiceLoginRequestValidationError{
			field:  "Email",
			reason: "value must be a valid email address",
			cause:  err,
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if utf8.RuneCountInString(m.GetPassword()) < 1 {
		err := UserServiceLoginRequestValidationError{
			field:  "Password",
			reason: "value length must be at least 1 runes",
		}
		if !all {
			return err
		}
		errors = append(errors, err)
	}

	if len(errors) > 0 {
		return UserServiceLoginRequestMultiError(errors)
	}

	return nil
}

func (m *UserServiceLoginRequest) _validateHostname(host string) error {
	s := strings.ToLower(strings.TrimSuffix(host, "."))

	if len(host) > 253 {
		return errors.New("hostname cannot exceed 253 characters")
	}

	for _, part := range strings.Split(s, ".") {
		if l := len(part); l == 0 || l > 63 {
			return errors.New("hostname part must be non-empty and cannot exceed 63 characters")
		}

		if part[0] == '-' {
			return errors.New("hostname parts cannot begin with hyphens")
		}

		if part[len(part)-1] == '-' {
			return errors.New("hostname parts cannot end with hyphens")
		}

		for _, r := range part {
			if (r < 'a' || r > 'z') && (r < '0' || r > '9') && r != '-' {
				return fmt.Errorf("hostname parts can only contain alphanumeric characters or hyphens, got %q", string(r))
			}
		}
	}

	return nil
}

func (m *UserServiceLoginRequest) _validateEmail(addr string) error {
	a, err := mail.ParseAddress(addr)
	if err != nil {
		return err
	}
	addr = a.Address

	if len(addr) > 254 {
		return errors.New("email addresses cannot exceed 254 characters")
	}

	parts := strings.SplitN(addr, "@", 2)

	if len(parts[0]) > 64 {
		return errors.New("email address local phrase cannot exceed 64 characters")
	}

	return m._validateHostname(parts[1])
}

// UserServiceLoginRequestMultiError is an error wrapping multiple validation
// errors returned by UserServiceLoginRequest.ValidateAll() if the designated
// constraints aren't met.
type UserServiceLoginRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceLoginRequestMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceLoginRequestMultiError) AllErrors() []error { return m }

// UserServiceLoginRequestValidationError is the validation error returned by
// UserServiceLoginRequest.Validate if the designated constraints aren't met.
type UserServiceLoginRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceLoginRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceLoginRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceLoginRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceLoginRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceLoginRequestValidationError) ErrorName() string {
	return "UserServiceLoginRequestValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceLoginRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceLoginRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceLoginRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceLoginRequestValidationError{}

// Validate checks the field values on UserServiceLoginResponse with the rules
// defined in the proto definition for this message. If any rules are
// violated, the first error encountered is returned, or nil if there are no violations.
func (m *UserServiceLoginResponse) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on UserServiceLoginResponse with the
// rules defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// UserServiceLoginResponseMultiError, or nil if none found.
func (m *UserServiceLoginResponse) ValidateAll() error {
	return m.validate(true)
}

func (m *UserServiceLoginResponse) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for AccessToken

	if len(errors) > 0 {
		return UserServiceLoginResponseMultiError(errors)
	}

	return nil
}

// UserServiceLoginResponseMultiError is an error wrapping multiple validation
// errors returned by UserServiceLoginResponse.ValidateAll() if the designated
// constraints aren't met.
type UserServiceLoginResponseMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m UserServiceLoginResponseMultiError) Error() string {
	msgs := make([]string, 0, len(m))
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m UserServiceLoginResponseMultiError) AllErrors() []error { return m }

// UserServiceLoginResponseValidationError is the validation error returned by
// UserServiceLoginResponse.Validate if the designated constraints aren't met.
type UserServiceLoginResponseValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e UserServiceLoginResponseValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e UserServiceLoginResponseValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e UserServiceLoginResponseValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e UserServiceLoginResponseValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e UserServiceLoginResponseValidationError) ErrorName() string {
	return "UserServiceLoginResponseValidationError"
}

// Error satisfies the builtin error interface
func (e UserServiceLoginResponseValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sUserServiceLoginResponse.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = UserServiceLoginResponseValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = UserServiceLoginResponseValidationError{}
