// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: auth/v1/auth.proto

package auth_v1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Запрос на регистрацию пользователя
type UserServiceRegisterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Email пользователя
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Пароль пользователя
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Имя пользователя
	Username      string `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceRegisterRequest) Reset() {
	*x = UserServiceRegisterRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceRegisterRequest) ProtoMessage() {}

func (x *UserServiceRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceRegisterRequest.ProtoReflect.Descriptor instead.
func (*UserServiceRegisterRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *UserServiceRegisterRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserServiceRegisterRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserServiceRegisterRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// Ответ на регистрацию пользователя
type UserServiceRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceRegisterResponse) Reset() {
	*x = UserServiceRegisterResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceRegisterResponse) ProtoMessage() {}

func (x *UserServiceRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceRegisterResponse.ProtoReflect.Descriptor instead.
func (*UserServiceRegisterResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

// Запрос на аутентификацию пользователя
type UserServiceLoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Логин пользователя
	Email string `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	// Пароль пользователя
	Password      string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceLoginRequest) Reset() {
	*x = UserServiceLoginRequest{}
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceLoginRequest) ProtoMessage() {}

func (x *UserServiceLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceLoginRequest.ProtoReflect.Descriptor instead.
func (*UserServiceLoginRequest) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *UserServiceLoginRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserServiceLoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

// Ответ на аутентификацию пользователя
type UserServiceLoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserServiceLoginResponse) Reset() {
	*x = UserServiceLoginResponse{}
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserServiceLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserServiceLoginResponse) ProtoMessage() {}

func (x *UserServiceLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserServiceLoginResponse.ProtoReflect.Descriptor instead.
func (*UserServiceLoginResponse) Descriptor() ([]byte, []int) {
	return file_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *UserServiceLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

var File_auth_v1_auth_proto protoreflect.FileDescriptor

const file_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x12auth/v1/auth.proto\x12\aauth.v1\x1a\x17validate/validate.proto\"\x85\x01\n" +
	"\x1aUserServiceRegisterRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\x12#\n" +
	"\busername\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\busername\"\x1d\n" +
	"\x1bUserServiceRegisterResponse\"]\n" +
	"\x17UserServiceLoginRequest\x12\x1d\n" +
	"\x05email\x18\x01 \x01(\tB\a\xfaB\x04r\x02`\x01R\x05email\x12#\n" +
	"\bpassword\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bpassword\"=\n" +
	"\x18UserServiceLoginResponse\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken2\xb2\x01\n" +
	"\vUserService\x12U\n" +
	"\bRegister\x12#.auth.v1.UserServiceRegisterRequest\x1a$.auth.v1.UserServiceRegisterResponse\x12L\n" +
	"\x05Login\x12 .auth.v1.UserServiceLoginRequest\x1a!.auth.v1.UserServiceLoginResponseBDZBgithub.com/poymanov/codemania-task-board/pkg/proto/auth/v1;auth_v1b\x06proto3"

var (
	file_auth_v1_auth_proto_rawDescOnce sync.Once
	file_auth_v1_auth_proto_rawDescData []byte
)

func file_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)))
	})
	return file_auth_v1_auth_proto_rawDescData
}

var (
	file_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
	file_auth_v1_auth_proto_goTypes  = []any{
		(*UserServiceRegisterRequest)(nil),  // 0: auth.v1.UserServiceRegisterRequest
		(*UserServiceRegisterResponse)(nil), // 1: auth.v1.UserServiceRegisterResponse
		(*UserServiceLoginRequest)(nil),     // 2: auth.v1.UserServiceLoginRequest
		(*UserServiceLoginResponse)(nil),    // 3: auth.v1.UserServiceLoginResponse
	}
)
var file_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.UserService.Register:input_type -> auth.v1.UserServiceRegisterRequest
	2, // 1: auth.v1.UserService.Login:input_type -> auth.v1.UserServiceLoginRequest
	1, // 2: auth.v1.UserService.Register:output_type -> auth.v1.UserServiceRegisterResponse
	3, // 3: auth.v1.UserService.Login:output_type -> auth.v1.UserServiceLoginResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_auth_v1_auth_proto_init() }
func file_auth_v1_auth_proto_init() {
	if File_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_auth_v1_auth_proto_rawDesc), len(file_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_auth_v1_auth_proto = out.File
	file_auth_v1_auth_proto_goTypes = nil
	file_auth_v1_auth_proto_depIdxs = nil
}
