// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/poymanov/codemania-task-board/board/internal/domain/task"
	mock "github.com/stretchr/testify/mock"
)

// NewTaskRepository creates a new instance of TaskRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskRepository {
	mock := &TaskRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// TaskRepository is an autogenerated mock type for the TaskRepository type
type TaskRepository struct {
	mock.Mock
}

type TaskRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *TaskRepository) EXPECT() *TaskRepository_Expecter {
	return &TaskRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type TaskRepository
func (_mock *TaskRepository) Create(ctx context.Context, newTask task.NewTask) (int, error) {
	ret := _mock.Called(ctx, newTask)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.NewTask) (int, error)); ok {
		return returnFunc(ctx, newTask)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.NewTask) int); ok {
		r0 = returnFunc(ctx, newTask)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task.NewTask) error); ok {
		r1 = returnFunc(ctx, newTask)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TaskRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type TaskRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newTask task.NewTask
func (_e *TaskRepository_Expecter) Create(ctx interface{}, newTask interface{}) *TaskRepository_Create_Call {
	return &TaskRepository_Create_Call{Call: _e.mock.On("Create", ctx, newTask)}
}

func (_c *TaskRepository_Create_Call) Run(run func(ctx context.Context, newTask task.NewTask)) *TaskRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.NewTask
		if args[1] != nil {
			arg1 = args[1].(task.NewTask)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskRepository_Create_Call) Return(n int, err error) *TaskRepository_Create_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *TaskRepository_Create_Call) RunAndReturn(run func(ctx context.Context, newTask task.NewTask) (int, error)) *TaskRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type TaskRepository
func (_mock *TaskRepository) Delete(ctx context.Context, id int) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type TaskRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TaskRepository_Expecter) Delete(ctx interface{}, id interface{}) *TaskRepository_Delete_Call {
	return &TaskRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *TaskRepository_Delete_Call) Run(run func(ctx context.Context, id int)) *TaskRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskRepository_Delete_Call) Return(err error) *TaskRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id int) error) *TaskRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAll provides a mock function for the type TaskRepository
func (_mock *TaskRepository) GetAll(ctx context.Context, filter task.GetAllFilter, sort task.GetAllSort) ([]task.Task, error) {
	ret := _mock.Called(ctx, filter, sort)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []task.Task
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.GetAllFilter, task.GetAllSort) ([]task.Task, error)); ok {
		return returnFunc(ctx, filter, sort)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, task.GetAllFilter, task.GetAllSort) []task.Task); ok {
		r0 = returnFunc(ctx, filter, sort)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]task.Task)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, task.GetAllFilter, task.GetAllSort) error); ok {
		r1 = returnFunc(ctx, filter, sort)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TaskRepository_GetAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAll'
type TaskRepository_GetAll_Call struct {
	*mock.Call
}

// GetAll is a helper method to define mock.On call
//   - ctx context.Context
//   - filter task.GetAllFilter
//   - sort task.GetAllSort
func (_e *TaskRepository_Expecter) GetAll(ctx interface{}, filter interface{}, sort interface{}) *TaskRepository_GetAll_Call {
	return &TaskRepository_GetAll_Call{Call: _e.mock.On("GetAll", ctx, filter, sort)}
}

func (_c *TaskRepository_GetAll_Call) Run(run func(ctx context.Context, filter task.GetAllFilter, sort task.GetAllSort)) *TaskRepository_GetAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 task.GetAllFilter
		if args[1] != nil {
			arg1 = args[1].(task.GetAllFilter)
		}
		var arg2 task.GetAllSort
		if args[2] != nil {
			arg2 = args[2].(task.GetAllSort)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TaskRepository_GetAll_Call) Return(tasks []task.Task, err error) *TaskRepository_GetAll_Call {
	_c.Call.Return(tasks, err)
	return _c
}

func (_c *TaskRepository_GetAll_Call) RunAndReturn(run func(ctx context.Context, filter task.GetAllFilter, sort task.GetAllSort) ([]task.Task, error)) *TaskRepository_GetAll_Call {
	_c.Call.Return(run)
	return _c
}

// IsExistsById provides a mock function for the type TaskRepository
func (_mock *TaskRepository) IsExistsById(ctx context.Context, id int) (bool, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for IsExistsById")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) (bool, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) bool); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// TaskRepository_IsExistsById_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsExistsById'
type TaskRepository_IsExistsById_Call struct {
	*mock.Call
}

// IsExistsById is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *TaskRepository_Expecter) IsExistsById(ctx interface{}, id interface{}) *TaskRepository_IsExistsById_Call {
	return &TaskRepository_IsExistsById_Call{Call: _e.mock.On("IsExistsById", ctx, id)}
}

func (_c *TaskRepository_IsExistsById_Call) Run(run func(ctx context.Context, id int)) *TaskRepository_IsExistsById_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *TaskRepository_IsExistsById_Call) Return(b bool, err error) *TaskRepository_IsExistsById_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *TaskRepository_IsExistsById_Call) RunAndReturn(run func(ctx context.Context, id int) (bool, error)) *TaskRepository_IsExistsById_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePosition provides a mock function for the type TaskRepository
func (_mock *TaskRepository) UpdatePosition(ctx context.Context, id int, position float64) error {
	ret := _mock.Called(ctx, id, position)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, float64) error); ok {
		r0 = returnFunc(ctx, id, position)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// TaskRepository_UpdatePosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePosition'
type TaskRepository_UpdatePosition_Call struct {
	*mock.Call
}

// UpdatePosition is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
//   - position float64
func (_e *TaskRepository_Expecter) UpdatePosition(ctx interface{}, id interface{}, position interface{}) *TaskRepository_UpdatePosition_Call {
	return &TaskRepository_UpdatePosition_Call{Call: _e.mock.On("UpdatePosition", ctx, id, position)}
}

func (_c *TaskRepository_UpdatePosition_Call) Run(run func(ctx context.Context, id int, position float64)) *TaskRepository_UpdatePosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 float64
		if args[2] != nil {
			arg2 = args[2].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *TaskRepository_UpdatePosition_Call) Return(err error) *TaskRepository_UpdatePosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *TaskRepository_UpdatePosition_Call) RunAndReturn(run func(ctx context.Context, id int, position float64) error) *TaskRepository_UpdatePosition_Call {
	_c.Call.Return(run)
	return _c
}
