// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/poymanov/codemania-task-board/auth/internal/domain/user"
	mock "github.com/stretchr/testify/mock"
)

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

type UserRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *UserRepository) EXPECT() *UserRepository_Expecter {
	return &UserRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UserRepository
func (_mock *UserRepository) Create(ctx context.Context, newUser user.NewUser) error {
	ret := _mock.Called(ctx, newUser)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, user.NewUser) error); ok {
		r0 = returnFunc(ctx, newUser)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UserRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - newUser user.NewUser
func (_e *UserRepository_Expecter) Create(ctx interface{}, newUser interface{}) *UserRepository_Create_Call {
	return &UserRepository_Create_Call{Call: _e.mock.On("Create", ctx, newUser)}
}

func (_c *UserRepository_Create_Call) Run(run func(ctx context.Context, newUser user.NewUser)) *UserRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 user.NewUser
		if args[1] != nil {
			arg1 = args[1].(user.NewUser)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UserRepository_Create_Call) Return(err error) *UserRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UserRepository_Create_Call) RunAndReturn(run func(ctx context.Context, newUser user.NewUser) error) *UserRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// IsDuplicateKey provides a mock function for the type UserRepository
func (_mock *UserRepository) IsDuplicateKey(err error) bool {
	ret := _mock.Called(err)

	if len(ret) == 0 {
		panic("no return value specified for IsDuplicateKey")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(error) bool); ok {
		r0 = returnFunc(err)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// UserRepository_IsDuplicateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDuplicateKey'
type UserRepository_IsDuplicateKey_Call struct {
	*mock.Call
}

// IsDuplicateKey is a helper method to define mock.On call
//   - err error
func (_e *UserRepository_Expecter) IsDuplicateKey(err interface{}) *UserRepository_IsDuplicateKey_Call {
	return &UserRepository_IsDuplicateKey_Call{Call: _e.mock.On("IsDuplicateKey", err)}
}

func (_c *UserRepository_IsDuplicateKey_Call) Run(run func(err error)) *UserRepository_IsDuplicateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 error
		if args[0] != nil {
			arg0 = args[0].(error)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *UserRepository_IsDuplicateKey_Call) Return(b bool) *UserRepository_IsDuplicateKey_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *UserRepository_IsDuplicateKey_Call) RunAndReturn(run func(err error) bool) *UserRepository_IsDuplicateKey_Call {
	_c.Call.Return(run)
	return _c
}
